version: '3'

services:
  bitcoin-tracer-mysql:
    container_name: bitcoin-tracer-mysql
    restart: always
    privileged: true
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: "980426"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "980321"
      MYSQL_DATABASE: "btc"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql